version: "3.7"

services:
  postgres:
    container_name: postgres
    image: "docker.io/library/postgres:15-alpine3.17"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_MULTIPLE_DATABASES=gateway
      - POSTGRES_USER=microservices
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/:z,U
      - ./pg-init-scripts:/docker-entrypoint-initdb.d:z

  gateway-go:
    container_name: gateway-go
    build:
      context: ../gateway-go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      - DATABASE_URL=postgres://microservices:password@postgres:5432/gateway?sslmode=disable
      - PORT=8080
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gateway-go
    restart: always
    environment:
      - BACKEND_API_URL=http://gateway-go:8080
      # set COOKIE_SECURE=true when serving over HTTPS
      - COOKIE_SECURE=false
