"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { TryItModal } from "@/components/TryItModal";
import { AppShell, Breadcrumb, StateBlock, Tabs, Field } from "@/components/ui";
import { useToast } from "@/hooks/useToast";
import { deleteApi, getApiDetail, saveApi } from "@/lib/api";
import type { ApiGateway } from "@/types";

const METHODS = ["GET", "POST", "PUT", "DELETE", "PATCH"];
const STATUSES = ["created", "published", "deprecated"];
type Form = { name: string; host: string; path: string; method: string; status: string; header: string; requireRequestParam: boolean; param: string; requireRequestBody: boolean };
const emptyForm: Form = { name: "", host: "", path: "", method: "GET", status: "created", header: "", requireRequestParam: false, param: "", requireRequestBody: false };

function fromApi(api: ApiGateway): Form { return { name: api.apiName, host: api.apiHost, path: api.apiPath, method: api.method, status: api.status ?? "created", header: (api.header ?? "").split(";").filter(Boolean).join("\n"), requireRequestParam: api.requireRequestParam ?? false, param: (api.param ?? "").split(";").filter(Boolean).join("\n"), requireRequestBody: api.requireRequestBody ?? false }; }
function list(text: string) { return text.split("\n").map((s) => s.trim()).filter(Boolean).join(";"); }

export default function ApiDetailPage() {
  const { identifier } = useParams<{ identifier: string }>(); const router = useRouter();
  const [api, setApi] = useState<ApiGateway | null>(null); const [form, setForm] = useState(emptyForm); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [tryOpen, setTryOpen] = useState(false); const { showToast, view: toast } = useToast();
  const load = useCallback(async () => { if (!identifier) return; setLoading(true); setError(""); try { const detail = await getApiDetail(identifier); setApi(detail); setForm(fromApi(detail)); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load API"); } finally { setLoading(false); } }, [identifier]);
  useEffect(() => { void load(); }, [load]);
  function update<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function save() { if (!api) return; setSaving(true); try { await saveApi({ apiIdentifier: api.apiIdentifier, name: form.name.trim(), host: form.host.trim(), path: form.path.trim(), method: form.method, status: form.status, header: list(form.header), requireRequestBody: form.requireRequestBody, requireRequestParam: form.requireRequestParam, param: list(form.param) }); showToast("API changes saved successfully!"); await load(); } catch (e) { showToast(e instanceof Error ? e.message : "Save failed", "error"); } finally { setSaving(false); } }
  async function remove() { if (!api || !window.confirm(`Delete "${api.apiName}"? This action cannot be undone.`)) return; try { await deleteApi(api.apiIdentifier); router.replace("/home"); } catch (e) { showToast(e instanceof Error ? e.message : "Delete failed", "error"); } }
  if (loading) return <AppShell><StateBlock title="Loading..." /></AppShell>;
  if (error || !api) return <AppShell><StateBlock title="API not found" detail={error} error /><button className="btn btn-outline back-button" onClick={() => router.push("/home")}>← Back to Dashboard</button></AppShell>;
  return <AppShell><Breadcrumb section="API List" current={form.name} onHome={() => router.push("/home")} /><div className="page-tabs"><Tabs active="api" onChange={(tab) => tab === "store" && router.push("/home")} /></div><div className="card-glass detail-card"><div className="api-summary"><Field label="API Name"><input className="input-field" placeholder="API name" value={form.name} onChange={(e) => update("name", e.target.value)} /></Field><Field label="Method"><select className="input-field" value={form.method} onChange={(e) => update("method", e.target.value)}>{METHODS.map((method) => <option key={method}>{method}</option>)}</select></Field><Field label="Status"><select className="input-field" value={form.status} onChange={(e) => update("status", e.target.value)}>{STATUSES.map((status) => <option key={status}>{status}</option>)}</select></Field></div><div className="grid-3 detail-grid"><Field label="API Host"><input className="input-field" placeholder="https://api.example.com" value={form.host} onChange={(e) => update("host", e.target.value)} /></Field><Field label="API Path"><input className="input-field" placeholder="/v1/endpoint" value={form.path} onChange={(e) => update("path", e.target.value)} /></Field><Field label="API Identifier"><input className="input-field" value={api.apiIdentifier} disabled /></Field></div><div className="section-divider" /><div className="grid-3"><Field label="Allowed Request Headers"><textarea className="input-field" rows={5} placeholder={"x-api-key\nContent-Type"} value={form.header} onChange={(e) => update("header", e.target.value)} /></Field><Field label="Require Request Parameters"><input type="checkbox" checked={form.requireRequestParam} onChange={(e) => update("requireRequestParam", e.target.checked)} /><textarea className="input-field" rows={5} placeholder={"limit\nsize"} value={form.param} onChange={(e) => update("param", e.target.value)} disabled={!form.requireRequestParam} /></Field><Field label="Require Request Body"><input type="checkbox" checked={form.requireRequestBody} onChange={(e) => update("requireRequestBody", e.target.checked)} /><div className="empty-field">{form.requireRequestBody ? "Request body will be mandatory" : "(no required body)"}</div></Field></div></div><div className="page-actions"><button className="btn btn-ghost" onClick={() => router.push("/home")}>← Back</button><button className="btn btn-success" onClick={() => setTryOpen(true)}>▶ Try it Now!</button><button className="btn btn-primary" onClick={save} disabled={saving}>{saving ? "Saving..." : "Save Changes"}</button><button className="btn btn-danger" onClick={remove}>Delete API</button></div>{tryOpen && <TryItModal name={form.name} host={form.host} path={form.path} method={form.method} identifier={api.apiIdentifier} onClose={() => setTryOpen(false)} />}{toast}</AppShell>;
}
