"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { AppShell, Breadcrumb, StateBlock, Tabs } from "@/components/ui";
import { useToast } from "@/hooks/useToast";
import { deleteStore, getStoreDetail, regenerateSecret, saveStore } from "@/lib/api";
import type { StoreRs } from "@/types";

type Section = "general" | "apikeys" | "danger";
const sections: { key: Section; icon: string; label: string }[] = [{ key: "general", icon: "⚙️", label: "General" }, { key: "apikeys", icon: "🔑", label: "API Keys" }, { key: "danger", icon: "⚠️", label: "Danger Zone" }];
function maskKey(key: string) { return key.length <= 10 ? key : `${key.slice(0, 10)}${"•".repeat(12)}`; }

export default function EditStoreAccountPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { showToast, view: toast } = useToast();
  const [store, setStore] = useState<StoreRs | null>(null); const [name, setName] = useState(""); const [section, setSection] = useState<Section>("general"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [regenerating, setRegenerating] = useState(false);
  const load = useCallback(async () => { const storeId = Number.parseInt(id ?? "", 10); if (!Number.isInteger(storeId) || storeId <= 0) { setError("Invalid store id"); setLoading(false); return; } setLoading(true); try { const detail = await getStoreDetail(storeId); setStore(detail); setName(detail.storeName); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load store"); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function save() { if (!store) return; setSaving(true); try { const updated = await saveStore({ storeId: store.id, storeName: name.trim() }); setStore(updated); showToast("Store account updated successfully!"); } catch (e) { showToast(e instanceof Error ? e.message : "Save failed", "error"); } finally { setSaving(false); } }
  async function remove() { if (!store || !window.confirm(`Delete "${store.storeName}"? This cannot be undone.`)) return; try { await deleteStore(store.id); router.replace("/home"); } catch (e) { showToast(e instanceof Error ? e.message : "Delete failed", "error"); } }
  async function regenerate() { if (!store || !window.confirm("Regenerate the API key for this store? The old key will stop working.")) return; setRegenerating(true); try { setStore(await regenerateSecret(store.id)); showToast("New API key generated!"); } catch (e) { showToast(e instanceof Error ? e.message : "Regeneration failed", "error"); } finally { setRegenerating(false); } }
  async function copyKey() { if (!store?.secretKey) return; try { await navigator.clipboard.writeText(store.secretKey); showToast("Key copied!"); } catch { showToast("Could not copy key", "error"); } }
  if (loading) return <AppShell><StateBlock title="Loading..." /></AppShell>;
  if (error || !store) return <AppShell><StateBlock title="Store not found" detail={error} error /><button className="btn btn-outline back-button" onClick={() => router.push("/home")}>← Back to Dashboard</button></AppShell>;
  return <AppShell><Breadcrumb section="Store Account" current={store.storeName} onHome={() => router.push("/home")} /><div className="page-tabs"><Tabs active="store" onChange={(tab) => tab === "api" && router.push("/home")} /></div><div className="store-layout"><aside className="card-glass store-sidebar"><strong>{store.storeName}</strong><span className="text-muted text-sm">{store.clientId}</span><div className="section-divider" /><nav className="sidebar-menu">{sections.map((item) => <button key={item.key} className={`sidebar-item ${section === item.key ? "active" : ""}`} onClick={() => setSection(item.key)}><span className="sidebar-icon">{item.icon}</span>{item.label}</button>)}</nav></aside><main className="card-glass store-panel">{section === "general" && <General name={name} clientId={store.clientId} saving={saving} onName={setName} onSave={save} onCancel={() => router.push("/home")} />}{section === "apikeys" && <Keys store={store} regenerating={regenerating} onRegenerate={regenerate} onCopy={copyKey} />}{section === "danger" && <Danger onDelete={remove} />}</main></div>{toast}</AppShell>;
}

function General({ name, clientId, saving, onName, onSave, onCancel }: { name: string; clientId: string; saving: boolean; onName: (value: string) => void; onSave: () => void; onCancel: () => void }) { return <><header className="page-header"><div><div className="page-title">General Settings</div><div className="page-subtitle">Update the name of your store account.</div></div></header><div className="stack-form"><label className="form-group"><span className="form-label">Store Name</span><input className="input-field" value={name} onChange={(e) => onName(e.target.value)} placeholder="My Store Name" /></label><label className="form-group"><span className="form-label">Client ID</span><input className="input-field" value={clientId ?? ""} disabled /></label></div><div className="page-actions"><button className="btn btn-ghost" onClick={onCancel}>Cancel</button><button className="btn btn-primary" onClick={onSave} disabled={saving}>{saving ? "Saving..." : "Save Changes"}</button></div></>; }
function Keys({ store, regenerating, onRegenerate, onCopy }: { store: StoreRs; regenerating: boolean; onRegenerate: () => void; onCopy: () => void }) { return <><header className="page-header"><div><div className="page-title">API Keys</div><div className="page-subtitle">Treat this key like a password. Share it only with your server.</div></div><button className="btn btn-primary btn-sm" onClick={onRegenerate} disabled={regenerating}>{regenerating ? "Generating..." : "+ Regenerate Key"}</button></header>{store.secretKey ? <div className="key-stack"><div className="key-row"><code>{maskKey(store.secretKey)}</code><button className="btn btn-ghost btn-sm" onClick={onCopy}>Copy</button></div><p className="text-muted text-sm">Regenerating the key immediately invalidates the previous one.</p></div> : <StateBlock title="No API key yet" detail="Click Regenerate Key to create one." empty={<div className="empty-icon">🔑</div>} />}</>; }
function Danger({ onDelete }: { onDelete: () => void }) { return <><header className="page-header"><div><div className="page-title danger-title">Danger Zone</div><div className="page-subtitle">Irreversible and destructive actions.</div></div></header><div className="danger-card"><div><strong>Delete Store Account</strong><p>Once deleted, all data associated with this store will be permanently removed.</p></div><button className="btn btn-danger" onClick={onDelete}>Delete Store</button></div></>; }
